
project_id = "frvjnuuqacrrrvrhzhuj"

[functions.submit-feedback]
verify_jwt = false

[functions.content-enhancer]
verify_jwt = false

[functions.task-ai-suggestions]
verify_jwt = true

[functions.mindmap-ai]
verify_jwt = false

[functions.document-ai-chat]
verify_jwt = false

[functions.study-buddy-chat]
verify_jwt = false
