// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://frvjnuuqacrrrvrhzhuj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZydmpudXVxYWNycnJ2cmh6aHVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzNTEzMTksImV4cCI6MjA1ODkyNzMxOX0.4iDaD2ntPsVUe4lQbSvipMtFwmb99YMvhxuDNz_DGx4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);